[package]
name = "kanban-min-term"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kanban-min-api = { path = "../kanban-min-api/" }
